# Base image
FROM python:3.9-slim-buster

# Set working directory
WORKDIR /var/www

# Update and install required packages
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install pip and Django
RUN python -m pip install --upgrade pip && \
    pip install django

# Copy project files to working directory
COPY . /var/www/

# Expose port 8000 for the Django development server
EXPOSE 8000

# Start Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
